/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Cliente;
import fatec.poo.model.ItemPedido;
import fatec.poo.model.Pedido;
import fatec.poo.model.Pessoa;
import fatec.poo.model.Produto;
import fatec.poo.model.Vendedor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EdCarlosMateusNunesVictorLembo
 */
public class GuiEmitirPedido extends javax.swing.JFrame {

    /**
     * Creates new form GuiEmitirPedido
     */
    public GuiEmitirPedido(ArrayList<Pedido> ep, ArrayList<Pessoa> pes, ArrayList<Produto> prod, ArrayList<ItemPedido> itped) {
        initComponents();
        cadPed = ep;
        cadCliVend = pes;
        cadProd = prod;
        cadItemPed = itped;
        modTblItemPedido = (DefaultTableModel) tblItemPedido.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private static boolean isNumeric(String c) {
        try {
            Long.parseLong(c);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    ;
         
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpnPedido = new javax.swing.JPanel();
        lblNumPedido = new javax.swing.JLabel();
        txtNumPedido = new javax.swing.JTextField();
        btnNumPedido = new javax.swing.JButton();
        lblDataPedido = new javax.swing.JLabel();
        txtDataPedido = new javax.swing.JFormattedTextField();
        lblFormaPagamento = new javax.swing.JLabel();
        cbxFormaPagamento = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lblCpfCli = new javax.swing.JLabel();
        txtCpfCli = new javax.swing.JFormattedTextField();
        btnNumCpfCli = new javax.swing.JButton();
        lblNomeCliente = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNomeVend = new javax.swing.JLabel();
        btnNumCpfVend = new javax.swing.JButton();
        txtCpfVend = new javax.swing.JFormattedTextField();
        lblCpfVend = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblDescProd = new javax.swing.JLabel();
        btnNumCodProd = new javax.swing.JButton();
        lblCodProd = new javax.swing.JLabel();
        txtCodProd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtQtdeVendida = new javax.swing.JTextField();
        btnAdicionarItem = new javax.swing.JButton();
        btnRemoverItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemPedido = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblValTotal = new javax.swing.JLabel();
        lblQtdeItensPed = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emitir Pedido");

        JpnPedido.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido"));

        lblNumPedido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNumPedido.setText("Número do Pedido");

        txtNumPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumPedidoActionPerformed(evt);
            }
        });

        btnNumPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnNumPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumPedidoActionPerformed(evt);
            }
        });

        lblDataPedido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDataPedido.setText("Data do Pedido");

        try {
            txtDataPedido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataPedido.setEnabled(false);

        lblFormaPagamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFormaPagamento.setText("Forma de Pagamento");

        cbxFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A vista" }));
        cbxFormaPagamento.setEnabled(false);

        javax.swing.GroupLayout JpnPedidoLayout = new javax.swing.GroupLayout(JpnPedido);
        JpnPedido.setLayout(JpnPedidoLayout);
        JpnPedidoLayout.setHorizontalGroup(
            JpnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNumPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblDataPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblFormaPagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxFormaPagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JpnPedidoLayout.setVerticalGroup(
            JpnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnPedidoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(JpnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JpnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDataPedido)
                        .addComponent(lblFormaPagamento)
                        .addComponent(cbxFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNumPedido)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Cliente"));

        lblCpfCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCpfCli.setText("CPF Cliente");

        try {
            txtCpfCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfCli.setEnabled(false);

        btnNumCpfCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnNumCpfCli.setEnabled(false);
        btnNumCpfCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumCpfCliActionPerformed(evt);
            }
        });

        lblNomeCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblCpfCli)
                .addGap(18, 18, 18)
                .addComponent(txtCpfCli, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNumCpfCli, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNumCpfCli, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCpfCli)
                        .addComponent(txtCpfCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Vendedor"));

        lblNomeVend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnNumCpfVend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnNumCpfVend.setEnabled(false);
        btnNumCpfVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumCpfVendActionPerformed(evt);
            }
        });

        try {
            txtCpfVend.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfVend.setEnabled(false);

        lblCpfVend.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCpfVend.setText("CPF Vendedor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblCpfVend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCpfVend, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNumCpfVend, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNomeVend, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNumCpfVend, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCpfVend)
                        .addComponent(txtCpfVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNomeVend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens do Pedido"));

        lblDescProd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnNumCodProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnNumCodProd.setEnabled(false);
        btnNumCodProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumCodProdActionPerformed(evt);
            }
        });

        lblCodProd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCodProd.setText("Código Produto");

        txtCodProd.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Qtde Vendida");

        txtQtdeVendida.setEnabled(false);

        btnAdicionarItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnAdicionarItem.setText("Adicionar Item");
        btnAdicionarItem.setEnabled(false);
        btnAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarItemActionPerformed(evt);
            }
        });

        btnRemoverItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/rem.png"))); // NOI18N
        btnRemoverItem.setText("Remover Item");
        btnRemoverItem.setEnabled(false);
        btnRemoverItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverItemActionPerformed(evt);
            }
        });

        tblItemPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Prec. Unit.", "Qtde. Vend.", "SubTotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblItemPedido);

        jLabel8.setText("Valor Total do Pedido");

        jLabel9.setText("Quantidades de Itens Pedidos");

        lblValTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblQtdeItensPed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblCodProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNumCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDescProd, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtdeVendida))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(btnAdicionarItem)
                        .addGap(28, 28, 28)
                        .addComponent(btnRemoverItem)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblValTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(lblQtdeItensPed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCodProd))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnNumCodProd, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                                .addComponent(lblDescProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtQtdeVendida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdicionarItem)
                    .addComponent(btnRemoverItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(lblValTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblQtdeItensPed, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(177, 177, 177))
        );

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setMnemonic('S');
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setMnemonic('E');
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setMnemonic('A');
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnIncluir.setMnemonic('I');
        btnIncluir.setText("Incluir");
        btnIncluir.setEnabled(false);
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JpnPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JpnPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnIncluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNumPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumPedidoActionPerformed
        String numPed = txtNumPedido.getText();

        if (isNumeric(numPed)) {
            int x;
            for (x = 0; x < cadPed.size(); x++) {
                if (((Pedido) cadPed.get(x)).getNumero().equals(txtNumPedido.getText())) {
                    break;
                }
            }
            if (x < cadPed.size()) {
                posPed = x;
            } else {
                posPed = -1;
            }

            if (posPed >= 0) {
                txtNumPedido.setText((cadPed.get(posPed)).getNumero());
                txtDataPedido.setText((cadPed.get(posPed)).getDataEmissao());
                cbxFormaPagamento.setSelectedIndex(0);

                txtCpfCli.setText((cadCliVend.get(posCli)).getCpf());
                lblNomeCliente.setText((cadCliVend.get(posCli)).getNome());
                txtCpfVend.setText((cadCliVend.get(posVend)).getCpf());
                lblNomeVend.setText((cadCliVend.get(posVend)).getNome());

                for (int i = 0; i < cadItemPed.size(); i++) {
                    String row[] = {
                        cadPed.get(posPed).getItensPedido(i).getProduto().getCodigo(),
                        cadPed.get(posPed).getItensPedido(i).getProduto().getDescricao(),
                        String.valueOf(cadPed.get(posPed).getItensPedido(i).getProduto().getPreco()),
                        String.valueOf(cadPed.get(posPed).getItensPedido(i).getQtdeVendida()),
                        String.valueOf((cadPed.get(posPed).getItensPedido(i).getProduto().getPreco() * cadPed.get(posPed).getItensPedido(i).getQtdeVendida()))

                    };

                    modTblItemPedido.addRow(row);
                    valTotal += (cadPed.get(posPed).getItensPedido(i).getProduto().getPreco() * cadPed.get(posPed).getItensPedido(i).getQtdeVendida());
                    qtdItensPed += cadPed.get(posPed).getItensPedido(i).getQtdeVendida();
                }

                lblValTotal.setText(String.valueOf(valTotal));
                lblQtdeItensPed.setText(String.valueOf(qtdItensPed));

                txtNumPedido.setEnabled(false);
                btnNumPedido.setEnabled(false);
                txtDataPedido.setEnabled(true);
                cbxFormaPagamento.setEnabled(true);
                txtCpfCli.setEnabled(true);
                btnNumCpfCli.setEnabled(true);
                txtCpfVend.setEnabled(true);
                btnNumCpfVend.setEnabled(true);
                txtCodProd.setEnabled(true);
                btnNumCodProd.setEnabled(true);
                txtQtdeVendida.setEnabled(true);

                btnAdicionarItem.setEnabled(true);
                btnRemoverItem.setEnabled(true);
                btnAlterar.setEnabled(true);
                btnExcluir.setEnabled(true);
            } else {
                btnNumPedido.setEnabled(false);
                txtDataPedido.setEnabled(true);
                cbxFormaPagamento.setEnabled(true);
                txtCpfCli.setEnabled(true);
                btnNumCpfCli.setEnabled(true);
                txtDataPedido.requestFocus();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Digite um código válido!");
            txtNumPedido.requestFocus();
        }


    }//GEN-LAST:event_btnNumPedidoActionPerformed

    private void btnNumCodProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumCodProdActionPerformed
        String codigo = txtCodProd.getText();
        if (isNumeric(codigo) == true) {
            int i;
            for (i = 0; i < cadProd.size(); i++) {
                if (((Produto) cadProd.get(i)).getCodigo().equals(txtCodProd.getText())) {
                    break;
                }
            }
            if (i < cadProd.size()) {
                posProd = i;
            } else {
                posProd = -1;
            }

            if (posProd >= 0) {
                txtCodProd.setText(((Produto) cadProd.get(posProd)).getCodigo());
                lblDescProd.setText(cadProd.get(posProd).getDescricao());

                txtQtdeVendida.setEnabled(true);
                btnAdicionarItem.setEnabled(true);
                btnRemoverItem.setEnabled(true);
                txtQtdeVendida.requestFocus();

            } else {
                JOptionPane.showMessageDialog(null, "Produto não encontrado!");
                txtCodProd.requestFocus();
                btnAdicionarItem.setEnabled(false);
                btnRemoverItem.setEnabled(true);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Digite um código válido!");
            txtCodProd.requestFocus();
        }
    }//GEN-LAST:event_btnNumCodProdActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnNumCpfCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumCpfCliActionPerformed
        int i;
        String cpfFormatted;
        for (i = 0; i < cadCliVend.size(); i++) {
            if (cadCliVend.get(i) instanceof Cliente) {
                if (((Pessoa) cadCliVend.get(i)).getCpf().equals(txtCpfCli.getText())) {

                    break;
                }
            }
        }

        cpfFormatted = txtCpfCli.getText().replace("-", "").replace(".", "");
        if (Pessoa.validarCPF(cpfFormatted)) {
            if (i < cadCliVend.size()) {
                posCli = i;
            } else {
                posCli = -1;
            }

            if (posCli >= 0) {
                p = new Pedido(txtNumPedido.getText(),
                        txtDataPedido.getText());
                txtCpfCli.setText(((Cliente) cadCliVend.get(posCli)).getCpf());
                lblNomeCliente.setText(((Cliente) cadCliVend.get(posCli)).getNome());
                p.setCliente((Cliente) cadCliVend.get(posCli));

                txtDataPedido.setEnabled(false);
                txtCpfCli.setEnabled(false);
                btnNumCpfCli.setEnabled(false);
                txtCpfVend.setEnabled(true);
                btnNumCpfVend.setEnabled(true);
                txtCpfVend.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Cliente não encontrado!");
                txtCpfCli.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "CPF Inválido!");
            txtCpfCli.requestFocus();
        }
    }//GEN-LAST:event_btnNumCpfCliActionPerformed

    private void btnNumCpfVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumCpfVendActionPerformed
        int i;
        String cpfFormatted;
        for (i = 0; i < cadCliVend.size(); i++) {
            if (cadCliVend.get(i) instanceof Vendedor) {
                if (((Pessoa) cadCliVend.get(i)).getCpf().equals(txtCpfVend.getText())) {

                    break;
                }
            }
        }

        cpfFormatted = txtCpfVend.getText().replace("-", "").replace(".", "");
        if (Pessoa.validarCPF(cpfFormatted)) {
            if (i < cadCliVend.size()) {
                posVend = i;
            } else {
                posVend = -1;
            }

            if (posVend >= 0) {

                txtCpfVend.setText(((Vendedor) cadCliVend.get(posVend)).getCpf());
                lblNomeVend.setText(((Vendedor) cadCliVend.get(posVend)).getNome());
                p.setVendedor((Vendedor) cadCliVend.get(posVend));

                txtCpfVend.setEnabled(false);
                btnNumCpfVend.setEnabled(false);
                txtCodProd.setEnabled(true);
                btnNumCodProd.setEnabled(true);
                txtCodProd.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Vendedor não encontrado!");
                txtCpfVend.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "CPF Inválido!");
            txtCpfVend.requestFocus();
        }
    }//GEN-LAST:event_btnNumCpfVendActionPerformed

    private void btnAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarItemActionPerformed

        double qtdVend = Double.parseDouble(txtQtdeVendida.getText());
        if (qtdVend == 0) {
            JOptionPane.showMessageDialog(null, "Digite uma quantidade valida!");
        } else {
            if (qtdVend > (cadProd.get(posProd).getQtdeEstoque())) {
                JOptionPane.showMessageDialog(null, "Estoque Insuficiente!");
            } else {

                ip = new ItemPedido(posProd, qtdVend, cadProd.get(posProd));
                if (cadProd.get(posProd).getPreco() * qtdVend > (((Cliente) cadCliVend.get(posCli)).getLimiteDisp())) {
                    JOptionPane.showMessageDialog(null, "Limite Insuficiente!");
                } else {
                    //p.setCliente((Cliente) cadCliVend.get(posCli));
                    //p.setVendedor((Vendedor) cadCliVend.get(posVend));

                    p.addItensPedido(ip);
                    cadItemPed.add(ip);

                    String row[] = {txtCodProd.getText(),
                        lblDescProd.getText(),
                        String.valueOf(cadProd.get(posProd).getPreco()),
                        txtQtdeVendida.getText(),
                        String.valueOf(cadProd.get(posProd).getPreco() * Double.parseDouble(txtQtdeVendida.getText()))
                    };

                    modTblItemPedido.addRow(row);

                    modTblItemPedido.setValueAt(String.valueOf(cadProd.get(posProd).getPreco() * qtdVend),
                            modTblItemPedido.getRowCount() - 1, 4);
                    for (int i = 0; i < tblItemPedido.getRowCount(); i++) {
                        valTotal = valTotal + Double.parseDouble(((String) tblItemPedido.getValueAt(i, 4)).replace(",", "."));

                        qtdItensPed = qtdItensPed + Double.parseDouble((String) tblItemPedido.getValueAt(i, 3));
                    }
                    lblValTotal.setText(String.valueOf(valTotal));
                    lblQtdeItensPed.setText(String.valueOf(qtdItensPed));

                    valTotal = 0;
                    qtdItensPed = 0;
                }
                if (tblItemPedido.getRowCount() > 0) {
                    btnIncluir.setEnabled(true);
                }
            }
        }

    }//GEN-LAST:event_btnAdicionarItemActionPerformed

    private void btnRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverItemActionPerformed
        if (tblItemPedido.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "A linha não foi selecionada", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else {
            modTblItemPedido.removeRow(tblItemPedido.getSelectedRow());
        }
    }//GEN-LAST:event_btnRemoverItemActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (posPed >= 0) {
            cadPed.remove(posPed);
            posPed = -1;
        }

        txtNumPedido.setText(null);
        txtCodProd.setText(null);
        txtDataPedido.setText(null);
        cbxFormaPagamento.setSelectedIndex(0);
        txtCpfCli.setText(null);
        lblNomeCliente.setText(null);
        txtCpfVend.setText(null);
        lblNomeVend.setText(null);
        txtCodProd.setText(null);
        lblDescProd.setText(null);
        txtQtdeVendida.setText(null);
        lblValTotal.setText(null);
        lblQtdeItensPed.setText(null);
        txtNumPedido.setText(null);

        txtNumPedido.setEnabled(true);
        txtDataPedido.setEnabled(false);
        txtCpfCli.setEnabled(false);
        btnNumCpfCli.setEnabled(false);
        txtCpfVend.setEnabled(false);
        btnNumCpfVend.setEnabled(false);
        txtQtdeVendida.setEnabled(false);
        txtCodProd.setEnabled(false);
        btnNumCodProd.setEnabled(false);
        btnAdicionarItem.setEnabled(false);
        btnRemoverItem.setEnabled(false);
        btnIncluir.setEnabled(false);
        btnNumPedido.setEnabled(false);
        cbxFormaPagamento.setEnabled(false);
        txtNumPedido.requestFocus();

        btnNumPedido.setEnabled(true);
        modTblItemPedido.setRowCount(0);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed

        ((Vendedor) cadCliVend.get(posVend)).addPedido(p);
        cadPed.add(p);

        txtNumPedido.setText(null);
        txtCodProd.setText(null);
        txtDataPedido.setText(null);
        cbxFormaPagamento.setSelectedIndex(0);
        txtCpfCli.setText(null);
        lblNomeCliente.setText(null);
        txtCpfVend.setText(null);
        lblNomeVend.setText(null);
        txtCodProd.setText(null);
        lblDescProd.setText(null);
        txtQtdeVendida.setText(null);
        lblValTotal.setText(null);
        lblQtdeItensPed.setText(null);
        txtNumPedido.setText(null);

        txtQtdeVendida.setEnabled(false);
        txtCodProd.setEnabled(false);
        btnNumCodProd.setEnabled(false);
        btnAdicionarItem.setEnabled(false);
        btnRemoverItem.setEnabled(false);
        btnIncluir.setEnabled(false);
        btnNumPedido.setEnabled(false);
        cbxFormaPagamento.setEnabled(false);
        txtNumPedido.requestFocus();

        btnNumPedido.setEnabled(true);
        modTblItemPedido.setRowCount(0);
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        cadPed.get(posPed).setDataPagto(txtDataPedido.getText());
        cadPed.get(posPed).setFormaPagto(Boolean.parseBoolean(String.valueOf(cbxFormaPagamento.getSelectedItem())));

        //txtDataPedido.setText((cadPed.get(posPed)).getDataEmissao());
        //cbxFormaPagamento.setSelectedIndex(0);
        /*  if((cadPed.get(posPed)).isFormaPagto()) {
                    rbtVista.setSelected();
                } else {
                    rbtPrazo.setSelected();
                }
        
        if (combobox.getSelectedItem().equals("A Vista")) 
         int iAns = iNum1 + iNum2;
        else if (combobox.getSelectedItem().equals("A Prazo")) 
         int iAns = iNum1 - iNum2;
         */
        /* p.setCliente((Cliente) cadCliVend.get(posCli));
        p.setVendedor((Vendedor) cadCliVend.get(posVend));
         */
        
        txtNumPedido.setText(null);
        txtCodProd.setText(null);
        txtDataPedido.setText(null);
        cbxFormaPagamento.setSelectedIndex(0);
        txtCpfCli.setText(null);
        lblNomeCliente.setText(null);
        txtCpfVend.setText(null);
        lblNomeVend.setText(null);
        txtCodProd.setText(null);
        lblDescProd.setText(null);
        txtQtdeVendida.setText(null);
        lblValTotal.setText(null);
        lblQtdeItensPed.setText(null);
        txtNumPedido.setText(null);

        txtNumPedido.setEnabled(true);
        txtDataPedido.setEnabled(false);
        txtCpfCli.setEnabled(false);
        btnNumCpfCli.setEnabled(false);
        txtCpfVend.setEnabled(false);
        btnNumCpfVend.setEnabled(false);
        txtQtdeVendida.setEnabled(false);
        txtCodProd.setEnabled(false);
        btnNumCodProd.setEnabled(false);
        btnAdicionarItem.setEnabled(false);
        btnRemoverItem.setEnabled(false);
        btnIncluir.setEnabled(false);
        btnNumPedido.setEnabled(false);
        cbxFormaPagamento.setEnabled(false);
        txtNumPedido.requestFocus();

        btnNumPedido.setEnabled(true);
        modTblItemPedido.setRowCount(0);


    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtNumPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpnPedido;
    private javax.swing.JButton btnAdicionarItem;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnNumCodProd;
    private javax.swing.JButton btnNumCpfCli;
    private javax.swing.JButton btnNumCpfVend;
    private javax.swing.JButton btnNumPedido;
    private javax.swing.JButton btnRemoverItem;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbxFormaPagamento;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodProd;
    private javax.swing.JLabel lblCpfCli;
    private javax.swing.JLabel lblCpfVend;
    private javax.swing.JLabel lblDataPedido;
    private javax.swing.JLabel lblDescProd;
    private javax.swing.JLabel lblFormaPagamento;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeVend;
    private javax.swing.JLabel lblNumPedido;
    private javax.swing.JLabel lblQtdeItensPed;
    private javax.swing.JLabel lblValTotal;
    private javax.swing.JTable tblItemPedido;
    private javax.swing.JTextField txtCodProd;
    private javax.swing.JFormattedTextField txtCpfCli;
    private javax.swing.JFormattedTextField txtCpfVend;
    private javax.swing.JFormattedTextField txtDataPedido;
    private javax.swing.JTextField txtNumPedido;
    private javax.swing.JTextField txtQtdeVendida;
    // End of variables declaration//GEN-END:variables
    private double valTotal;
    private double qtdItensPed;
    private ArrayList<Pedido> cadPed;
    private ArrayList<Pessoa> cadCliVend;
    private ArrayList<Produto> cadProd;
    private ArrayList<ItemPedido> cadItemPed;
    private Pedido p;
    private ItemPedido ip;
    private int posPed;
    private int posVend;
    private int posCli;
    private int posProd;
    private DefaultTableModel modTblItemPedido;

}
