package fatec.poo.view;

import fatec.poo.model.ItemPedido;
import fatec.poo.model.Pedido;
import fatec.poo.model.Pessoa;
import fatec.poo.model.Produto;
import java.util.ArrayList;

/**
 *
 * @author EdCarlosMateusNunesVictorLembo
 */
public class GuiMenu extends javax.swing.JFrame {

    public GuiMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnbMenu = new javax.swing.JMenuBar();
        mnuCadastros = new javax.swing.JMenu();
        mniClientes = new javax.swing.JMenuItem();
        mniVendedores = new javax.swing.JMenuItem();
        mniProdutos = new javax.swing.JMenuItem();
        smnMenu = new javax.swing.JPopupMenu.Separator();
        mniSair = new javax.swing.JMenuItem();
        mnuPedido = new javax.swing.JMenu();
        mniEmitirPedido = new javax.swing.JMenuItem();
        mniConsultarComissaoVendedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Vendas");

        mnuCadastros.setText("Cadastros");

        mniClientes.setText("Clientes");
        mniClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniClientesActionPerformed(evt);
            }
        });
        mnuCadastros.add(mniClientes);

        mniVendedores.setText("Vendedores");
        mniVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVendedoresActionPerformed(evt);
            }
        });
        mnuCadastros.add(mniVendedores);

        mniProdutos.setText("Produtos");
        mniProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniProdutosActionPerformed(evt);
            }
        });
        mnuCadastros.add(mniProdutos);
        mnuCadastros.add(smnMenu);

        mniSair.setText("Sair");
        mniSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSairActionPerformed(evt);
            }
        });
        mnuCadastros.add(mniSair);

        mnbMenu.add(mnuCadastros);

        mnuPedido.setText("Pedido");

        mniEmitirPedido.setText("Emitir Pedido");
        mniEmitirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEmitirPedidoActionPerformed(evt);
            }
        });
        mnuPedido.add(mniEmitirPedido);

        mniConsultarComissaoVendedor.setText("Consutar Comissao Vendedor");
        mniConsultarComissaoVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConsultarComissaoVendedorActionPerformed(evt);
            }
        });
        mnuPedido.add(mniConsultarComissaoVendedor);

        mnbMenu.add(mnuPedido);

        setJMenuBar(mnbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniProdutosActionPerformed
        new GuiProduto(cadProd).setVisible(true);
    }//GEN-LAST:event_mniProdutosActionPerformed

    private void mniClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniClientesActionPerformed
        new GuiCliente(cadCliVend).setVisible(true);        
    }//GEN-LAST:event_mniClientesActionPerformed

    private void mniVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVendedoresActionPerformed
        new GuiVendedor(cadCliVend).setVisible(true);
    }//GEN-LAST:event_mniVendedoresActionPerformed

    private void mniSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_mniSairActionPerformed

    private void mniEmitirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEmitirPedidoActionPerformed
        new GuiEmitirPedido(cadPed, cadCliVend, cadProd, cadItemPed).setVisible(true);
    }//GEN-LAST:event_mniEmitirPedidoActionPerformed

    private void mniConsultarComissaoVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConsultarComissaoVendedorActionPerformed
        new GuiConsultarComissaoVendedor(cadCliVend, cadPed).setVisible(true);       
    }//GEN-LAST:event_mniConsultarComissaoVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mnbMenu;
    private javax.swing.JMenuItem mniClientes;
    private javax.swing.JMenuItem mniConsultarComissaoVendedor;
    private javax.swing.JMenuItem mniEmitirPedido;
    private javax.swing.JMenuItem mniProdutos;
    private javax.swing.JMenuItem mniSair;
    private javax.swing.JMenuItem mniVendedores;
    private javax.swing.JMenu mnuCadastros;
    private javax.swing.JMenu mnuPedido;
    private javax.swing.JPopupMenu.Separator smnMenu;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Pessoa> cadCliVend = new ArrayList<Pessoa>();
    private ArrayList<Produto> cadProd = new ArrayList<Produto>();
    private ArrayList<Pedido> cadPed = new ArrayList<Pedido>();
    private ArrayList<ItemPedido> cadItemPed = new ArrayList<ItemPedido>();
}
